### ISSUE TITLE
Updating whitelist

### ISSUE THREAD

**Issue by phuzz** [hpaolini/procon#23]
I'm using a subscription to a whitelist hosted on my own server. I've just added some domains and I'd like to update the whitelist.
Clicking the "Update Subscriptions" button in the preferences doesn't seem to do anything,the sites aren't added and I can see that the line in `prefs.js`, `extensions.procon.subscriptions.whitelist.sites`, hasn't changed. Also `extensions.procon.subscriptions.lastUpdateTime` doesn't change.

Am I doing something wrong with this button?

Also, would it be possible to change the 72 hour update time? A option to change it in the settings would be great.

**Comment by hpaolini** [comment]
Subscription lists are not appended to the local lists. In other words, if you have enabled subscriptions they should be working, but you don't necessarily see them in the preferences (aside from the subscription addresses) because they are maintained by whoever hosts them.

However, both your local lists and subscription lists can work together.

**Comment by phuzz** [comment]
I'm not using local lists, just subscriptions.
Is there any way to change the 72 hour refresh?

**Comment by hpaolini** [comment]
Not currently; I will add an option.
