### ISSUE TITLE
Multiprocess on Firefox 54+ compatibility

### ISSUE THREAD

**Issue by Draky50110** [hpaolini/procon#25]
Hi.

Your Firefox addon is not compatible with new Firefox 54+ feature : multiprocess (e10s).

Can you update it please ?

Thanks !

**Comment by hpaolini** [comment]
Hi there,

ProCon is already compatible with multiprocess Firefox; not sure what the deal is with Firefox dev version.

I hope migration to WebExtensions has not yet begun.

**Comment by hpaolini** [comment]
Please update using the install.xpi file on this repo. Let me know whether that fixes things up.

**Comment by Draky50110** [comment]
The addon page tells me it is not signed :(

**Comment by hpaolini** [comment]
Install it from [https://github.com/hpaolini/procon/blob/master/install.xpi](here) since I haven't signed it on the AMO yet.

**Comment by Draky50110** [comment]
Not working either.

**Comment by hpaolini** [comment]
Weird, working here on Firefox 55.0b2.

Anyways, submitted it as version 4.2.0 to the AMO for review. The update should appear as soon as they accept it.

**Comment by Draky50110** [comment]
Ok, thanks a lot :)

Good luck for Webextension process :)

**Comment by Draky50110** [comment]
4.2.0 still flaggeed as not compatible with multiprocess on Firefox 54.0

**Comment by hpaolini** [comment]
It's flagged as "unknown" but I wouldn't worry about it; it's been compatible with multi-process Firefox since version 4.0.0.

I've let them know, but I don't think it matters as almost all extensions are now flagged as "legacy" until they are migrated to web-extensions.

The reports causing ProCon to be flagged as such are for version 3.*.*, which users, for whatever reason, have not updated.

**Comment by Etcheguaray** [comment]
Firefox Quantum 57 is a DISASTER. Pro Con Latte is the #1 add-on I rely on to get through my workday. Its the best add-on ever developed. But now after Quantum (Oct 2) I have no idea what is now going on.  Nothing works! I've spent half of today trying to sort it out.  I've switched from ff 57 to ff 56, then to ff 47. I've even switched to Waterfox and it STILL doesn't work! Question: is there any version of Firefox or Waterfox which WILL work with Procon Latte and if so, WHAT version of Pro Con Latte is the one which is still functional? Look, I will gladly pay anyone $$ to fix this for me. Paypal standing by waiting! Help!

**Comment by yassine944** [comment]
> 
> 
> Firefox Quantum 57 is a DISASTER. Pro Con Latte is the #1 add-on I rely on to get through my workday. Its the best add-on ever developed. But now after Quantum (Oct 2) I have no idea what is now going on. Nothing works! I've spent half of today trying to sort it out. I've switched from ff 57 to ff 56, then to ff 47. I've even switched to Waterfox and it STILL doesn't work! Question: is there any version of Firefox or Waterfox which WILL work with Procon Latte and if so, WHAT version of Pro Con Latte is the one which is still functional? Look, I will gladly pay anyone $$ to fix this for me. Paypal standing by waiting! Help!

Hello Etcheguaray,
No need to pay anything to anyone. I don't know why Procon Latte didn't work for you, it works perfectly for me on WaterFox. Do you have a problem installing it or getting it to block content? You can also use other extensions that are compatible with Firefox Quantum like LeechBlock NG (free) or FoxFilter (paid).

**Comment by stephanelorrain** [comment]
It also works perfectly for me on WaterFox. 
However, on Firefox, I started using "Web Content Filter (within your Browser)" by serv-inc. However, it work differently since for each word found, a score is incremented until a certain limit is reached. Also, you can set "about:blank" as the "blockpage" if you want to hide the "reason" (keywords founds). But I prefer using Waterfox.
