### ISSUE TITLE
Can I censor Emoji?

### ISSUE THREAD

**Issue by SoupNerd** [hpaolini/procon#26]
I don't want to see Rainbow flags everywhere on Twitter. How do I hide them on my end?

**Comment by hpaolini** [comment]
I just checked and the problem with Twitter is that those are not actually emojis, but _images_ of emojis; that's why ProCon can't remove them. I believe they use their own images for consistency among different browsers, apps, and operating systems.

I'd use uBlock Origin to block Twitter's rainbow images ([https://abs.twimg.com/emoji/v2/72x72/1f3f3-fe0f-200d-1f308.png](https://abs.twimg.com/emoji/v2/72x72/1f3f3-fe0f-200d-1f308.png) and [https://abs.twimg.com/emoji/v2/72x72/1f308.png](https://abs.twimg.com/emoji/v2/72x72/1f308.png)), then ProCon to remove actual emojis on the rest of the web.

Add the these two items in your profanity filter to block the real emojis:

🌈
🏳️‍🌈

Hunter

**Comment by SoupNerd** [comment]
How do I use uBlock to get rid of the Rainbow images?

**Comment by hpaolini** [comment]
Use the element picker, see [https://github.com/gorhill/uBlock/wiki/Element-picker](https://github.com/gorhill/uBlock/wiki/Element-picker).
