### ISSUE TITLE
Not comptable with FF Quantum 57.0

### ISSUE THREAD

**Issue by globalogicom** [hpaolini/procon#31]
We love your plugin and have been using for many years and can't find any substitute for FF, please help and update for FF 57. THANKS!

**Comment by hpaolini** [comment]
Please see #27:

> At the moment there is no API to protect the add-on from being disabled/removed. Password-protection should be a must in a content filter; therefore, releasing a half-baked version of ProCon without it would not be as convenient.
> 
> If there is enough interest in the community, I might take some time to fully port it to a Web Extension. **However,** such version will definitely lack password-protection.

**Comment by hellwoodfire** [comment]
I used procon to protect my children. I am really sad that it is not working in FF57+.
Please, please, please!!!  please help us protect our children!

**Comment by dayentech** [comment]
If you would please do what you can to make this work with quantum.  I understand you are having problems with the passwords but something functioning would be great!  I use this to block my son from sites and preventing him from using keywords he uses to look up things I don't want him to see.

**Comment by nw-git** [comment]
+4 on getting Procon Latte working on Quantum. The extension could always be bypassed by starting Firefox in safe mode, however, something would definitely be better than having the extension disabled altogether (what currently happens). Thanks for your work on this invaluable extension- it definitely hasn't gone unnoticed.

**Comment by gipi85** [comment]
First, I want to give you a HUGE thank you for your remarkable and impressive work on ProCon Latte! It works nicely, blocking the filters directly on the search engines like Google or Bing. Also it provides black and white lists and protects all with a password. It is by far the BEST add-on for Firefox for this purpose!

It is for that reason that I signed in to GitHub, to encourage you to work on a new version with the same features also on the newer versions of Firefox (57+). 

If I have to pay 12,99 $ to FoxFilter, I prefer to pay 20 $ to you a new ProCon Latte! And so many people will do, because your software is the best, really.

I'm going to personally donate you that money because, given the price of the unsatisfactory competion, your add-on is worth that price at least.

**Comment by gipi85** [comment]
Dear mister Paolini, even if you are not allowed anymore to offer your ProCon Latte add-on for Firefox, due to the change in extension platform,

please,

could you still make it available for other Browsers based on Firefox, like PaleMoon, which presumably will continue to use the same extension system (the previous one)?

Thank you very much for taking time to read this and for your software. You really contributed to make the internet a better place for everyone.

P. S. I looked for a donation button to you everywhere, but I wasn't able to find it!

**Comment by gipi85** [comment]
I've found the button (it's at the end of the add-on page)! Looking for good news!

**Comment by Luigi-C** [comment]
Dear hpaolini,
the day when I realized that ProCon Latte won't work anymore with fireFox has been a very sad day.
I had succefully used ProCon Latte before to prevent people to get access to inappropriate web pages, and ProCon Latte had revealed the best Parental Control extention for FireFox.
Is there a chance to solve the problems preventing you from making the extention fully functional with FF Quantum?
Thank you very much for the effort you made till now, and the effort you will make in the future.

**Comment by hellwoodfire** [comment]
Procon work well in Waterfox.

**Comment by hpaolini** [comment]
@Luigi-C As stated before, starting from Firefox Quantum, the new extension engine breaks pretty much most of ProCon's code. The issue, however, is not that of coding everything again (although still very time-consuming), but that the result will not include any sort of uninstall/disable protection.

If anyone has any idea, suggestion, or wants to collaborate on a project please get in touch with me.

**Comment by Luigi-C** [comment]
I have just installed Firefox ESR, that's all ok, the old extensions are all working!

**Comment by Etcheguaray** [comment]
Please, it does not MATTER that 'password lock' is not enabled. Its perfectly okay. We need this add-on functional anyway, even without password! Come on...
