### ISSUE TITLE
Suggestion : block OPTIONS like ADDONS

### ISSUE THREAD

**Issue by Draky50110** [hpaolini/procon#7]
Hello.

Your addon block the access to ADDONS menu.
Is it possible to also block the whole OPTIONS menu ?

Thanks :)

**Comment by hpaolini** [comment]
Firefox's Options/Preferences don't really impact the purpose of the add-on. Why would you want to block them?

**Comment by Draky50110** [comment]
I understand :)

I'd like ProCon to transform into a complete parental control addon ;)
Because I don't want my kid to change the search engine or other options.

**Comment by hpaolini** [comment]
Blocking the preferences would really stretch it out a bit and, too be honest, wouldn't really be a perfect solution. Search engines can be added without opening the preferences anyways, and nothing would prevent a user from installing one of those "preference manager"-type add-ons from changing them.

Please consider that, at the moment the add-ons page is blocked because there is no other way to prevent this add-on from being disabled--it's really a temporary fix until I figure out how to prevent *only* ProCon from being disabled--just as in the previous versions--without impacting other extensions.

**Comment by Draky50110** [comment]
Ok, I understand :)
